export const CLIENT_MAX_SUPPORTED_BLOCK_VERSION = 0;

export const DEFAULT_PROGRAM_RETURN_CODE = 0;
export const DEFAULT_CARTESI_VM_MAX_CYCLES = 30000000000n;
export const SWARM_PING_INTERVAL = 10000;
