FROM golang:1.18 as go-ipfs-build

WORKDIR /app

RUN git clone "https://github.com/ipfs/kubo.git" -b v0.18.1
RUN cd kubo

WORKDIR /app/kubo

RUN go mod download

RUN CGO_ENABLED=0 make nofuse


FROM debian:bullseye-slim as kernel-base

ARG KERNEL_VERSION="5.5.19"
ARG KERNEL_URL="https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-${KERNEL_VERSION}.tar.gz"

WORKDIR /build/kernel

RUN apt update
RUN apt install -y \
  bc \
  bison \
  build-essential \
  cpio \
  flex \
  libelf-dev \
  libssl-dev \
  wget \
  gcc-x86-64-linux-gnu

RUN wget "$KERNEL_URL"
RUN tar xvzf "linux-${KERNEL_VERSION}.tar.gz" -C /build/kernel

FROM kernel-base as kernel-kvm
ARG KERNEL_VERSION="5.5.19"

WORKDIR "/build/kernel/linux-${KERNEL_VERSION}"

COPY src/verifier/validator-kernel-config "/build/kernel/linux-${KERNEL_VERSION}/.config"
RUN make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu- olddefconfig
RUN make -j $(nproc) ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu- bzImage


FROM kernel-base as kernel-nokvm
ARG KERNEL_VERSION="5.5.19"

WORKDIR "/build/kernel/linux-${KERNEL_VERSION}"

COPY src/verifier/validator-kernel-q35-nokvm-config "/build/kernel/linux-${KERNEL_VERSION}/.config"
RUN make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu- olddefconfig
RUN make -j $(nproc) ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu- bzImage


FROM rust:alpine3.16 AS merkle-tree-build

WORKDIR /src

RUN apk --no-cache add git musl-dev

RUN git clone https://github.com/tosichain/multithread-merkle-tree -b v1.0
 
WORKDIR /src/multithread-merkle-tree

RUN cargo fetch --locked

RUN cargo build --release

RUN cargo install --path . --root /opt/tosi

# Rust build stage
FROM rust:latest as rust-build

# Building qemu-run-task
WORKDIR /app/qemu-run-task
COPY ./src/verifier/qemu-run-task/Cargo.toml ./Cargo.toml
COPY ./src/verifier/qemu-run-task/src ./src
RUN cargo build --release

# Building qemu-test-task
WORKDIR /app/qemu-test-task
COPY ./src/verifier/qemu-test-task/Cargo.toml ./Cargo.toml
COPY ./src/verifier/qemu-test-task/src ./src
RUN cargo build --release

# Building prepopulate
WORKDIR /app/prepopulate
COPY ./src/verifier/prepopulate/Cargo.toml ./Cargo.toml
COPY ./src/verifier/prepopulate/src ./src
RUN cargo build --release

# Building grab-and-hash
WORKDIR /app/grab-and-hash
COPY ./src/verifier/grab-and-hash/Cargo.toml ./Cargo.toml
COPY ./src/verifier/grab-and-hash/src ./src
RUN cargo build --release

# =============================================================================
FROM alpine:3.16.0 as image

ARG KERNEL_VERSION="5.5.19"

RUN apk --no-cache add qemu-system-x86_64 qemu-accel-tcg-x86_64 openssh-server e2tools xxd libgomp boost1.77-serialization wget jq
COPY --from=go-ipfs-build "/app/kubo/cmd/ipfs/ipfs" "/usr/bin/ipfs"
RUN sed -i '/^#Port 22/s/^#//' /etc/ssh/sshd_config \
    && sed -i '/^#PasswordAuthentication/s/^#//' /etc/ssh/sshd_config \
    && sed -i '/^#PermitEmptyPasswords no/s/^#PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config \
    && sed -i '/^#PermitRootLogin prohibit-password/s/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && echo "root:Docker!" | chpasswd

WORKDIR /app

RUN --mount=type=cache,target=/fetchcache35 wget -c -P /fetchcache35 https://web3.link/loaderv2.squashfs && mkdir -p /data/prepopulate && cp /fetchcache35/* /data/prepopulate
RUN --mount=type=cache,target=/fetchcache35-car wget -c -P /fetchcache35-car https://web3.link/init_image.car && mkdir -p /data/prepopulate-car && cp /fetchcache35-car/* /data/prepopulate-car
RUN truncate -s 16384 /data/prepopulate/empty.16kb

COPY --from=kernel-kvm "/build/kernel/linux-${KERNEL_VERSION}/arch/x86/boot/bzImage" /app
COPY --from=kernel-kvm "/build/kernel/linux-${KERNEL_VERSION}/.config" /app
COPY --from=kernel-nokvm "/build/kernel/linux-${KERNEL_VERSION}/arch/x86/boot/bzImage" /app/bzImage-nokvm-q35
COPY --from=kernel-nokvm "/build/kernel/linux-${KERNEL_VERSION}/.config" /app/.config-nokvm
COPY --from=merkle-tree-build "/opt/tosi/bin/merkle-tree-hash" "/app//merkle-tree-hash"

RUN mkdir -p /opt/verifier

# Replace shell scripts with rust binary
COPY --from=rust-build /app/qemu-run-task/target/release/qemu-run-task /app/qemu-run-task
COPY --from=rust-build /app/qemu-test-task/target/release/qemu-test-task /app/qemu-test-task
COPY --from=rust-build /app/prepopulate/target/release/prepopulate /app/prepopulate
COPY --from=rust-build /app/grab-and-hash/target/release/grab-and-hash /app/grab-and-hash

COPY ./src/verifier/qemu-test-cid.sh /app/qemu-test-cid.sh
COPY ./src/verifier/ssh.sh /app/ssh.sh
COPY ./src/verifier/grab-dag-as-car-and-hash.sh /app/grab-dag-as-car-and-hash.sh

RUN chmod +x /app/ssh.sh /app/grab-and-hash /app/qemu-run-task /app/grab-dag-as-car-and-hash.sh /app/prepopulate /app/qemu-test-cid.sh

CMD [ "/app/ssh.sh" ]
