# Have to be used with -p option:
# docker compose --profile build -p tosi-chain -f docker-compose-tosi-node-testnet.yml build
version: "3.3"

services:
  client-base:
    extends:
      file: docker-compose/templates.yml
      service: client-base
  verifier:
    extends:
      file: docker-compose/templates.yml
      service: verifier

  # IPFS instance 2
  ipfs-2:
    extends:
      file: docker-compose/templates.yml
      service: ipfs-public
    volumes:
      - "./client-ipfs-db:/data/ipfs"

  db-2:
    extends:
      file: docker-compose/templates.yml
      service: db
    volumes:
      - "./client-db:/var/lib/mysql"

  # Client node.
  client:
    extends:
      file: docker-compose/templates.yml
      service: client

    depends_on:
      ipfs-2:
        condition: service_healthy
      db-2:
        condition: service_healthy

    ports:
      - "127.0.0.1:30001:30001" # For API

    environment:
      TOSI_MINTER_PUBKEY: "ab92bd04cb362bf07ce6380727fb956379963da44c6027fea2cbeddf516f7151320491a27b7f4df4106f94224641a6f4"
      TOSI_STAKE_POOL_PUBKEY: "a5a31c6de185d5fe861bca71bcc9b86d8ab27133e244afbe5ac988d3d622bcbf52a2ce0b84b129f32d92219919a34307"
      BLS_SEC_KEY: "${TOSI_CLIENT_BLS_SEC_KEY}"
      IPFS_HTTP_API_HOST: "ipfs-2"
      STORAGE_DB_PATH: "./tosi-blockchain-db"
      COORDINATOR_PUB_KEY: "8ea14bd457eaa9d91a4ad862f6252d67462232a5e3d88ea8a752875725e6e3843b2d1533cc507f59f4c732c266e52417"
      COORDINATOR_RPC_SERVER_ADDR: "https://coordinator.dev.tosichain.com/api"
      VERIFIER_HOST: "client-verifier"
      SYNC_ETH_RPC: "https://goerli-rollup.arbitrum.io/rpc"
      SYNC_ETH_CLAIM_CONTRACT_ADDRESS: "0x4731A0Dd87e637321D4E4980BeF351f992F14b77" # UUPSProxy contract.
      SYNC_PERIOD: 10000 # 10 seconds
      OFFCHAIN_DA_COMMITEE_SAMPLE_SIZE: 2
      API_PORT: 30001
      ROLE_IS_DA_SAMPLER: false
      DB_HOST: "db-2"
      DB_USER: "root"
      DB_PASSWORD: "example"
      DB_DB: "tosi"

  client-verifier:
    extends:
      file: docker-compose/templates.yml
      service: verifier-service

