

version: "3.3"
secrets:
  ipfs_swarm_key:
    file: swarm.key

services:

  localnet-base:
    extends:
      file: docker-compose/base.yml
      service: localnet-base

  verifier-service-base:
    extends:
        file: docker-compose/base.yml
        service: verifier-service-base

  coordinator-base:
    extends:
        file: docker-compose/base.yml
        service: coordinator-base

  client-base:
    extends:
      file: docker-compose/base.yml
      service: client-base


  localnet:
    extends:
      file: docker-compose/base.yml
      service: localnet
    

  coordinator-db:
    extends:
      file: docker-compose/base.yml
      service: db

  coordinator-ipfs:
    extends:
      file: docker-compose/base.yml
      service: ipfs-private
    ports:
      - "127.0.0.1:50011:5001" # For integration tests.

  coordinator:
    image: tosi-chain-coordinator-base:latest
    depends_on:
      localnet:
        condition: service_healthy
      coordinator-db:
        condition: service_healthy
      coordinator-ipfs:
        condition: service_healthy
    links:
      - localnet
      - coordinator-db
      - coordinator-ipfs
    ports:
      - "127.0.0.1:20001:20001" # For integration tests.
    volumes:
      - type: bind
        source: ./docker-compose/config/docker-compose-tosi-chain/coordinator.yml
        target: "/config/tosi-coordinator.yml"
    healthcheck:
      test: ["CMD-SHELL", "nc localhost 20001 < /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client-db:
    extends:
      file: docker-compose/base.yml
      service: db

  client-ipfs:
     extends:
      file: docker-compose/base.yml
      service: ipfs-private

  client-verifier-service:
    extends:
      file: docker-compose/base.yml
      service: verifier-service

  client:
    image: tosi-chain-client-base:latest
    depends_on:
      coordinator:
        condition: service_healthy
      client-db:
        condition: service_healthy
      client-ipfs:
        condition: service_healthy
    links:
      - coordinator
      - client-db
      - client-ipfs
      - client-verifier-service
    ports:
      - "127.0.0.1:30001:30001" # For integration tests.
    volumes:
      - type: bind
        source: ./docker-compose/config/docker-compose-tosi-chain/client.yml
        target: "/config/tosi-client.yml"
    healthcheck:
      test: ["CMD-SHELL", "nc localhost 30001 < /dev/null" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  
  
  verifier-1-db:
    extends:
      file: docker-compose/base.yml
      service: db

  verifier-1-ipfs:
    extends:
      file: docker-compose/base.yml
      service: ipfs-private

  verifier-1-verifier-service:
    extends:
      file: docker-compose/base.yml
      service: verifier-service

  verifier-1:
    image: tosi-chain-client-base:latest
    depends_on:
      coordinator:
        condition: service_healthy
      verifier-1-db:
        condition: service_healthy
      verifier-1-ipfs:
        condition: service_healthy
    links:
      - coordinator
      - verifier-1-db
      - verifier-1-ipfs
      - verifier-1-verifier-service
    ports:
      - "127.0.0.1:30002:30001" # For integration tests.
    volumes:
      - type: bind
        source: ./docker-compose/config/docker-compose-tosi-chain/verifier-1.yml
        target: "/config/tosi-client.yml"
  
  
  verifier-2-db:
    extends:
      file: docker-compose/base.yml
      service: db

  verifier-2-ipfs:
    extends:
      file: docker-compose/base.yml
      service: ipfs-private

  verifier-2-verifier-service:
    extends:
      file: docker-compose/base.yml
      service: verifier-service

  verifier-2:
    image: tosi-chain-client-base:latest
    depends_on:
      coordinator:
        condition: service_healthy
      verifier-2-db:
        condition: service_healthy
      verifier-2-ipfs:
        condition: service_healthy
    links:
      - coordinator
      - verifier-2-db
      - verifier-2-ipfs
      - verifier-2-verifier-service
    ports:
      - "127.0.0.1:30003:30001" # For integration tests.
    volumes:
      - type: bind
        source: ./docker-compose/config/docker-compose-tosi-chain/verifier-2.yml
        target: "/config/tosi-client.yml"
  
  
  verifier-3-db:
    extends:
      file: docker-compose/base.yml
      service: db

  verifier-3-ipfs:
    extends:
      file: docker-compose/base.yml
      service: ipfs-private

  verifier-3-verifier-service:
    extends:
      file: docker-compose/base.yml
      service: verifier-service

  verifier-3:
    image: tosi-chain-client-base:latest
    depends_on:
      coordinator:
        condition: service_healthy
      verifier-3-db:
        condition: service_healthy
      verifier-3-ipfs:
        condition: service_healthy
    links:
      - coordinator
      - verifier-3-db
      - verifier-3-ipfs
      - verifier-3-verifier-service
    ports:
      - "127.0.0.1:30004:30001" # For integration tests.
    volumes:
      - type: bind
        source: ./docker-compose/config/docker-compose-tosi-chain/verifier-3.yml
        target: "/config/tosi-client.yml"
  
