version: "3.3"

services:

  client-base:
    extends:
      file: docker-compose/base.yml
      service: client-base

  verifier-service-base:
    extends:
      file: docker-compose/base.yml
      service: verifier-service-base

  client-db:
    extends:
      file: docker-compose/base.yml
      service: db
    volumes:
      - ./client-db-mainnet:/var/lib/mysql

  client-ipfs:
    extends:
      file: docker-compose/base.yml
      service: ipfs-public
    volumes:
      - ./client-ipfs-db-mainnet:/data/ipfs

  client-verifier-service:
    extends:
      file: docker-compose/base.yml
      service: verifier-service

  client:
    extends:
      file: docker-compose/base.yml
      service: client-base
    depends_on:
      client-db:
        condition: service_healthy
      client-ipfs:
        condition: service_healthy
    ports:
      - "127.0.0.1:30001:30001" # For sync test.
    volumes:
      - type: bind
        source: ./docker-compose/config/docker-compose-tosi-node-mainnet/client.yml
        target: "/config/tosi-client.yml"