name: Mainnet Sync CI

on: [push]

jobs:
  mainnet-sync:
    runs-on: [self-hosted, linux, x64]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - name: "mainnet sync"
            compose-file: docker-compose-tosi-node-mainnet.yml
            logfile: mainnet-sync
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Stop all containers
        run: |
          docker ps -q | awk '{print $1}' | grep -v CONTAINER | xargs -L1 -r docker stop
      - name: Rming all containers
        run: |
          docker ps -q | awk '{print $1}' | grep -v CONTAINER | xargs -L1 -r docker rm
      - name: Clean up docker envionment
        run: |
          docker volume prune -f
          docker volume ls -qf dangling=true | xargs -L1 -r docker volume rm
      - name: Check docker-compose version
        run: |
          docker compose version
      - name: Set up caching
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build the containers
        run: |
          docker compose --profile build -p tosi-chain -f ${{ matrix.compose-file }} build
      - name: Stop and remove any leftovers
        run: |
          docker compose -p tosi-chain -f ${{ matrix.compose-file }} down --remove-orphans
      - name: Check the status of the running docker containers
        run: |
          docker ps -a
      - name: Start mainnet
        run: |
          docker compose -p tosi-chain -f ${{ matrix.compose-file }} up --remove-orphans --detach --wait
      - name: sync logs
        if: ${{ always() }}
        run: |
          docker compose -p tosi-chain -f ${{ matrix.compose-file }} logs --timestamps -f &> ${{ matrix.logfile }}.log &
      - name: Wait for sync
        env:
          COMPOSE_FILE: ${{ matrix.compose-file }}
        run: |
          COUNTER=0
          until [[ "$(docker compose -p tosi-chain -f $COMPOSE_FILE exec -e API_PORT=30001 client npx ts-node --files ./src/checkSync.ts)" = "true" ]]; do
            echo "Waiting for sync to complete..."
            docker compose -p tosi-chain -f ${{ matrix.compose-file }} exec client-ipfs ipfs swarm peers
            sleep 5
            COUNTER=$(($COUNTER + 1))
            if [ x$COUNTER == x100 ]; then
               exit 1
            fi
          done
          echo "Sync completed successfully."
      - name: Save log
        if:  ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.logfile }}.log
          path: ${{ matrix.logfile }}.log
      - name: Stop mainnet
        if:  ${{ always() }}
        run: |
          docker compose -p tosi-chain -f ${{ matrix.compose-file }} down
