name: datachain continous integration tests
on: [push]
jobs:
  test_coordinator:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "client sync on localnet"
            citest: test:tosi.client.sync
            logfile: client
            composefile: docker-compose-tosi-chain.yml
          - name: "da committee on localnet"
            citest: test:tosi.da.committee.test
            logfile: da
            composefile: docker-compose-tosi-chain.yml
          - name: "client sync on simul"
            citest: test:tosi.client.sync
            logfile: client
            composefile: docker-compose-tosi-coordinator-simul.yml
          - name: "da committee on simul"
            citest: test:tosi.da.committee.test
            logfile: da
            composefile: docker-compose-tosi-coordinator-simul.yml
    runs-on: [self-hosted, linux, x64]
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}'
      cancel-in-progress: true
    steps:
      - name: Dump Contexts
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$RUNNER_CONTEXT"
      # git context is the default for actions but this will fail for docker in
      # a monorepo with multiple (docker) build contexts. As such, we must
      # checkout...
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Stop all containers
        run: |
          docker ps -q | awk '{print $1}' | grep -v CONTAINER | xargs -L1 -r docker stop
      - name: Rming all containers
        run: |
          docker ps -q | awk '{print $1}' | grep -v CONTAINER | xargs -L1 -r docker rm
      - name: Clean up docker envionment
        run: |
          docker volume prune -f
      - name: Check docker-compose version
        run: |
          docker compose version

      - name: Set up caching
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build the containers
        run: |
          docker compose --profile build -p tosi-chain -f ${{ matrix.composefile }} build
      - name: Stop and remove any leftovers
        run: |
          docker compose -p tosi-chain -f ${{ matrix.composefile }} down --remove-orphans
      - name: Check the status of the running docker containers
        run: |
          docker ps -a
      - name: Start the containers
        run: |
          docker compose -p tosi-chain -f ${{ matrix.composefile }} up --remove-orphans --detach --wait
      - name: Build the test containers
        run: |
          sudo docker build -f src/tosi_tests/Dockerfile -t test:1.0 .
      - name: Test contracts
        run: docker run --network=host test:1.0 npx hardhat test
      - name: Run integration tests - tosi client
        run: |
          docker run --network=host test:1.0 yarn ${{ matrix.citest }}
      - name: Grab logs
        if: ${{ always() }}
        run: |
          docker compose -p tosi-chain -f ${{ matrix.composefile }} logs &> logs.${{ matrix.composefile }}.${{ matrix.logfile }}.txt
          gzip -9 logs.${{ matrix.composefile }}.${{ matrix.logfile }}.txt
      - name: Upload integration logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: integration-logs.${{ matrix.composefile }}.${{ matrix.logfile }}
          path: logs.${{ matrix.composefile }}.${{ matrix.logfile }}.txt.gz
      - name: Stop the containers
        run: |
          docker compose -p tosi-chain -f ${{ matrix.composefile }} down
